In [2]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.model_selection import train_test_split


%matplotlib inline

iris_flowers = pd.read_csv('OneDrive/Desktop/Machine learning/IRIS_flower_dataset.csv')

In [21]:
iris_flowers.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [3]:
iris_flowers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [4]:
iris_flowers.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [5]:
# defining X and y variables
y = pd.factorize(iris_flowers.species)[0]

features = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
X = iris_flowers[features]

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [7]:
X.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [8]:
iris_flowers.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [9]:
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.3, random_state=0)

train_X.shape

In [10]:
train_X

sepal_length  sepal_width  petal_length  petal_width
60            5.0          2.0           3.5          1.0
116           6.5          3.0           5.5          1.8
144           6.7          3.3           5.7          2.5
119           6.0          2.2           5.0          1.5
108           6.7          2.5           5.8          1.8
..            ...          ...           ...          ...
9             4.9          3.1           1.5          0.1
103           6.3          2.9           5.6          1.8
67            5.8          2.7           4.1          1.0
117           7.7          3.8           6.7          2.2
47            4.6          3.2           1.4          0.2

[105 rows x 4 columns]

In [11]:
train_y.shape

(105,)

In [12]:
print(test_X)

     sepal_length  sepal_width  petal_length  petal_width
114           5.8          2.8           5.1          2.4
62            6.0          2.2           4.0          1.0
33            5.5          4.2           1.4          0.2
107           7.3          2.9           6.3          1.8
7             5.0          3.4           1.5          0.2
100           6.3          3.3           6.0          2.5
40            5.0          3.5           1.3          0.3
86            6.7          3.1           4.7          1.5
76            6.8          2.8           4.8          1.4
71            6.1          2.8           4.0          1.3
134           6.1          2.6           5.6          1.4
51            6.4          3.2           4.5          1.5
73            6.1          2.8           4.7          1.2
54            6.5          2.8           4.6          1.5
63            6.1          2.9           4.7          1.4
37            4.9          3.1           1.5          0.1
78            

In [13]:
test_X.shape

(45, 4)

## Using Entropy as criterion

In [15]:
classifier = RandomForestClassifier(n_jobs=2, n_estimators = 7, criterion = 'entropy', random_state=0)
classifier.fit(train_X, train_y)

RandomForestClassifier(criterion='entropy', n_estimators=7, n_jobs=2,
                       random_state=0)

In [16]:
predictions = classifier.predict(test_X)
predictions

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0,
       0], dtype=int64)

In [17]:
# Viewing the predicted probability of the first 10 observations
classifier.predict_proba(test_X)[0:10]

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [18]:
# # Create a set of unique predicted labels for convenience
# unique_predictions = set(predictions)

# matched_labels = {}  # Store matches (predicted: true)
# for pred in unique_predictions:
#     # Find the first occurrence of the prediction in train_y
#     matching_index = train_y.index[train_y == pred].to_list()[0]
#     matched_labels[pred] = train_y[matching_index]

# # Use the matched_labels dictionary to access true labels based on predictions
# predicted_label = "Iris-virginica"  # Example prediction
# true_label = matched_labels.get(predicted_label, None)  # Handle potential absence
# print(f"Predicted label: {predicted_label}, True label: {true_label}")

preds = test_y[predictions]
preds[0:5]

array([0, 1, 2, 0, 2], dtype=int64)

In [19]:
# Creating a confusion matrix
pd.crosstab(test_y, preds, rownames=['Actual names'], colnames=['Predicted names'])

Predicted names   0   1   2
Actual names               
0                 0   0  16
1                 1  17   0
2                11   0   0

In [23]:
from sklearn.metrics import classification_report, accuracy_score

print("Score: {}".format(accuracy_score(test_y, predictions)))

Score: 0.9777777777777777


In [24]:
print("Score: {}".format(classification_report(test_y, predictions)))

Score:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.94      0.97        18
           2       0.92      1.00      0.96        11

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



# Using gini as criterion

In [27]:
classifier_2 = RandomForestClassifier(n_jobs=2, n_estimators = 7, criterion = 'gini', random_state=0)
classifier_2.fit(train_X, train_y)

RandomForestClassifier(n_estimators=7, n_jobs=2, random_state=0)

In [28]:
predictions_2 = classifier_2.predict(test_X)
predictions_2

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0,
       0], dtype=int64)

In [29]:
classifier_2.predict_proba(test_X)[0:10]

array([[0.        , 0.        , 1.        ],
       [0.        , 0.85714286, 0.14285714],
       [1.        , 0.        , 0.        ],
       [0.        , 0.        , 1.        ],
       [1.        , 0.        , 0.        ],
       [0.        , 0.        , 1.        ],
       [1.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 1.        , 0.        ]])

In [30]:
preds_2 = test_y[predictions]
preds_2[0:5]

array([0, 1, 2, 0, 2], dtype=int64)

In [31]:
# Creating a confusion matrix
pd.crosstab(test_y, preds_2, rownames=['Actual names'], colnames=['Predicted names'])

Predicted names   0   1   2
Actual names               
0                 0   0  16
1                 1  17   0
2                11   0   0

In [32]:
print("Score: {}".format(accuracy_score(test_y, predictions_2)))

Score: 0.9555555555555556


In [34]:
print("Score: {}".format(classification_report(test_y, predictions_2)))

Score:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.94      0.94      0.94        18
           2       0.91      0.91      0.91        11

    accuracy                           0.96        45
   macro avg       0.95      0.95      0.95        45
weighted avg       0.96      0.96      0.96        45



## Using log loss as criterion

In [37]:
classifier_3 = RandomForestClassifier(n_jobs=2, n_estimators = 7, criterion = 'log_loss', random_state=0)
classifier_3.fit(train_X, train_y)

RandomForestClassifier(criterion='log_loss', n_estimators=7, n_jobs=2,
                       random_state=0)

In [38]:
predictions_3 = classifier_2.predict(test_X)
predictions_3

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0,
       0], dtype=int64)

In [39]:
classifier_3.predict_proba(test_X)[0:10]

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [40]:
preds_3 = test_y[predictions]
preds_3[0:5]

array([0, 1, 2, 0, 2], dtype=int64)

In [41]:
# Creating a confusion matrix
pd.crosstab(test_y, preds_3, rownames=['Actual names'], colnames=['Predicted names'])

Predicted names   0   1   2
Actual names               
0                 0   0  16
1                 1  17   0
2                11   0   0

In [43]:
print("Score: {}".format(accuracy_score(test_y, predictions_3)))

Score: 0.9777777777777777


In [45]:
print("Score: {}".format(classification_report(test_y, predictions_3)))

Score:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.94      0.97        18
           2       0.92      1.00      0.96        11

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



## Conclusion

**Entropy** and **log loss** are the best criterion for the Iris flower dataset when using Random Forest Classification